import Testing

@testable import AdventOfCode
@testable import _2024

@Test func day08_example_part1() { #expect(Day08(data: example1).part1() == 14) }
@Test func day08_example_part2() {
    #expect(Day08(data: example1).part2() == 34)
    #expect(Day08(data: example2).part2() == 9)
}

// @Test func day08_part1() { #expect(Day08().part1() == 336) }
// @Test func day08_part2() { #expect(Day08().part2() == 1131) }

private let example1 = """
    ............
    ........0...
    .....0......
    .......0....
    ....0.......
    ......A.....
    ............
    ............
    ........A...
    .........A..
    ............
    ............
    """

private let example2 = """
    T.........
    ...T......
    .T........
    ..........
    ..........
    ..........
    ..........
    ..........
    ..........
    ..........
    """
