import Testing

@testable import AdventOfCode
@testable import _2024

@Test("Day 8, Part 1 (Example)") private func day_08_example_part1() {
  #expect(Day08(data: example1).part1() == 14)
}

@Test("Day 8, Part 2 (Example)") private func day_08_example_part2() {
  #expect(Day08(data: example2).part2() == 9)
  #expect(Day08(data: example1).part2() == 34)
}

@Test("Day 8, Part 1") private func day_08_part1() {
  #expect(Day08().part1() == 336)
}

@Test("Day 8, Part 2") private func day_08_part2() {
  #expect(Day08().part2() == 1131)
}

private let example1 = """
  ............
  ........0...
  .....0......
  .......0....
  ....0.......
  ......A.....
  ............
  ............
  ........A...
  .........A..
  ............
  ............
  """

private let example2 = """
  T.........
  ...T......
  .T........
  ..........
  ..........
  ..........
  ..........
  ..........
  ..........
  ..........
  """
