import Testing

@testable import AdventOfCode
@testable import _2024

@Test func day06_example_part1() { #expect(Day06(data: example).part1() == 41) }
@Test func day06_example_part2() { #expect(Day06(data: example).part2() == 6) }

// @Test func day06_part1() { #expect(Day06().part1() == 4722) }
// @Test func day06_part2() { #expect(Day06().part2() == 1602) }

private let example = """
    ....#.....
    .........#
    ..........
    ..#.......
    .......#..
    ..........
    .#..^.....
    ........#.
    #.........
    ......#...
    """
