import Testing

@testable import AdventOfCode
@testable import _2023

@Test func day11_example_part1() { #expect(Day11(data: example).part1() == 374) }

// @Test func day11_part1() { #expect(Day11().part1() == 9_329_143) }
// @Test func day11_part2() { #expect(Day11().part2() == 710_674_907_809) }

private let example = """
    ...#......
    .......#..
    #.........
    ..........
    ......#...
    .#........
    .........#
    ..........
    .......#..
    #...#.....
    """
