import Testing

@testable import AdventOfCode
@testable import _2025

@Test func day07_example_part1() { #expect(Day07(data: example).part1() == 21) }
@Test func day07_example_part2() { #expect(Day07(data: example).part2() == 40) }

@Test func day07_part1() { #expect(Day07().part1() == 1649) }
@Test func day07_part2() { #expect(Day07().part2() == 16_937_871_060_075) }

private let example = """
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............
    """
